### ISSUE TITLE
Request: Allow for theming of the MacOS title bar

### ISSUE THREAD

**Issue by CillySu** [AnKing-VIP/AnkiRecolor#10]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.46
```

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

#### Solution

It would be nice if, like in many other programs such as VSCode it were possible to style the title bar in MacOS, I believe this is possible within the Qt framework. See below for an example of a styled titlebar

#### More information

![image](https://user-images.githubusercontent.com/73595592/157513883-53fedbd2-2e78-40d1-ae54-c5ec94862c09.png)

**Comment by BlueGreenMagick** [comment]
It seems like the title bar is drawn by the OS instead of qt, and it doesn't seem easy to change it in Python + Qt.

https://forum.qt.io/topic/72335/changing-window-titlebar-colour-in-macos

If I'm wrong and there's an easy way to change titlebar color, I'm willing to implement it!
