### ISSUE TITLE
HEX color code

### ISSUE THREAD

**Issue by MightyBooman** [AnKing-VIP/AnkiRecolor#21]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.55 Qt6
```

#### Problem case

n/a

#### Solution

It would be great to have an option to be able to search for colors using HEX codes. I found a color theme online that I want to use, but I have to find a workaround in order to find and add the desired colors within the ReColor addon

#### More information

Just to be thorough -- the HEX code option could be added as an option at the top of the window in the screenshot below.

![image](https://user-images.githubusercontent.com/98279951/210140273-cc646176-def2-45c4-9b44-ef8a22c7e98a.png)

**Comment by BlueGreenMagick** [comment]
You can edit the hex color if you click 'advanced' button in the add-on config
