### ISSUE TITLE
Recolor showing weird colours - presets not working, colour not really changing.

### ISSUE THREAD

**Issue by k102494** [AnKing-VIP/AnkiRecolor#32]
#### Problem description

I've installed recolor on anki 2.1.66, I think, whatever the newest one is, and none of the premade colourschemes are working. Some create a mild change but still not really usable, and lots of them just don't change the colour at all.

I'm putting in photos of:
me applying a theme
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/143787192/fa797af8-0770-468e-80e6-c4115273bcf3)
the result of the application
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/143787192/e62a1255-858d-47e6-8933-5f83135880d6)
copying and pasting in an entire code for a particular theme
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/143787192/2c4a6668-9e7c-4b2f-a4df-4b287aa2fba8)
the result of applying that
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/143787192/9570efcc-d318-4c3b-9b25-7ae257f1b597)
the card editor in this theme - still looks sort of terrible
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/143787192/c44c2e80-7df2-470f-a2fc-30ad256bd871)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.66
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by BlueGreenMagick** [comment]
For themes with `(dark)` in their name, you need to change Anki to dark mode in Anki's preferences.
Atleast some of them are still good enough to use in 2.1.66.

**Comment by k102494** [comment]
Thank you! That fixed it
