### ISSUE TITLE
Some things won't change colour

### ISSUE THREAD

**Issue by lfcannie** [AnKing-VIP/AnkiRecolor#34]
#### Problem description

I have changed the colours of everything however whenever i edit a card and the background of some of the window does not change

![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/156346137/43c4441c-e948-448a-9997-3759b7109d36)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [n/a] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.66 (tried other versions to see if issue changes but does not)
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by lfcannie** [comment]
this issue also remains whenever i have tried other themes

**Comment by BlueGreenMagick** [comment]
Fixed! All pages should be colored fine when the new update goes live.

@AnKingMed Can you upload the new version [v3.0](https://github.com/AnKing-VIP/AnkiRecolor/releases/tag/3.0) to AnkiWeb?

**Comment by AnKingMed** [comment]
Thanks for updating it! @abdnh would you mind uploading this?

**Comment by abdnh** [comment]
Uploaded.
