### ISSUE TITLE
Bug when I press browse

### ISSUE THREAD

**Issue by Semmyboy123** [AnKing-VIP/AnkiRecolor#35]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Opened anki, then pressed browse and an anki error message pops up that takes me to a troubleshooting guide

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.12.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-10.15.7-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.toolbar", line 411, in _linkHandler
  File "aqt.toolbar", line 429, in _browseLinkHandler
  File "aqt.main", line 1240, in onBrowse
  File "aqt", line 136, in open
  File "aqt.browser.browser", line 139, in __init__
  File "aqt.browser.browser", line 639, in setupSidebar
  File "aqt.browser.sidebar.tree", line 95, in __init__
  File "aqt.browser.sidebar.tree", line 107, in _setup_style
  File "aqt.theme", line 192, in var
TypeError: tuple indices must be integers or slices, not str

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
ReColor ['688199788', 2023-04-27T23:19, '1.8', mod]
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1771074083 688199788

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Symbols As You Type ['2040501954', 2024-01-20T05:42, 'None', '']

```

**Comment by BlueGreenMagick** [comment]
It's because you are using an older version of the add-on intended for Anki versions earlier than v2.1.55. Update your add-on and things should work fine! (except some colors not being colored correctly #34)
