### ISSUE TITLE
The theme is back to Anki default during reviewing cards🙏

### ISSUE THREAD

**Issue by CaptainDead** [AnKing-VIP/AnkiRecolor#36]
#### Problem description

*Normally, When we are at the home page, where we can see all the decks, The theme is in action perfectly, Even if I am using a custom background, there is a slight low opacity theme color on it, like see the screenshot - 
![Screenshot 2024-03-10 144131](https://github.com/AnKing-VIP/AnkiRecolor/assets/139457914/9019a3a3-6413-40ad-b6d9-eaf48c48a366)

But, When I study a deck, The theme color is only in effect in the bottom and top, the middle is back to normal anki default color, there is no low opacity theme color here on the top of the Background, like there was in the home page, look at the screen shot - 
![Screenshot 2024-03-10 144150](https://github.com/AnKing-VIP/AnkiRecolor/assets/139457914/2d60a824-a1e6-4fc0-9737-c2c4eaa0b1d3)

I really would have loved it if the theme was in action during the decks are being studied as thats where we moslty spend our time in anki and not at home page.
If possible, please tell me how I can make the theme color to be visible while studying deck or if there is no such option, I would request to implant it as I think its an important thing.
Thanks*

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
```
Version ⁨23.12.1 (1a1d4d54)⁩
```

**Comment by CaptainDead** [comment]
Like the theme not working when we are studying the cards is so weird cuz there is lowkey no point of this addon cuz we spend majority of time studying the cards and not at the home page of anki, but yeah it changes the browser too so thats cool, I really wish that it was possible to have the theme working when we study the cards

**Comment by BlueGreenMagick** [comment]
It's because your note type styling is setting background color to something else.

Go to `Tools > Manage Note Types`, for all the note types that you use, click `Cards`, view `Styling`, and remove all lines that look like this `background-color: white;` or `background: white;`.

**Comment by CaptainDead** [comment]
OMG thanks man and sorry if I sounded rude when I said "there is lowkey no point of this addon" 🙏

The first thing you said is the right one, 
I use "Anking" (cloze) and "Basic-Anking" Note types and they have background colors, I tried using the default "Basic" note type and the theme color was there when I reviewed that card💯🎉 

So I will change the BG color of Anking and Basic-Anking notetypes, I dont think there is a way of changing this BG color from the 'Anki Note types' Addon so I will change them from 'styling' option 


To make sure I am not messing things up, I will share What I am chaning so you can confirm if I did it right

I am deleting the text that is selected, its what I am supposed to remove right?
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/139457914/89393afd-64e8-4e43-9491-088c3dc3ee86)

and there is also a Night mode version of the same so I am also removing that part from here - 
![image](https://github.com/AnKing-VIP/AnkiRecolor/assets/139457914/62905dc9-f158-474f-b302-fef56339e640)

**Comment by CaptainDead** [comment]
Great it worked; Now I just want to confirm that I didn't remove anything important, so did I? I did the same with other note types and now everything is perfect, thanks a lot bro🙏🔥💖

**Comment by BlueGreenMagick** [comment]
Yep, those are indeed what you needed to remove. Glad to hear everything's working fine for you.
