### ISSUE TITLE
Opacity Slider on Mac Color Picker

### ISSUE THREAD

**Issue by ebaber** [AnKing-VIP/AnkiRecolor#8]
Please add code so that an opacity slider shows up on the color picker for Mac.

![u549m2h](https://user-images.githubusercontent.com/20386705/157367010-8cedc5be-05d0-4111-a777-4363faa8d6a5.png)

**Comment by BlueGreenMagick** [comment]
Is this to change the opacity of the window(i.e. translucent dialog), or do you have some other use for it?

**Comment by ebaber** [comment]
In my case, I'd like to have an option to make the most recently selected deck background entirely translucent, so I can see the background image without interruption (essentially, reverting to how it appeared before the most recent update). Currently, I have to choose an opaque coordinating color, which is a bit of an annoyance since I like a random image to appear each time I open up Anki. For instance, here is how my Anki loaded up the first time after the newest update:
![20mawm3dguk81](https://user-images.githubusercontent.com/20386705/157906747-8348c283-ea08-4174-b698-949d8834f57f.png)
I imagine there are lots of other aesthetic uses for the slider too, such as giving themes a softer or more ethereal look.
